// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeajpoChs9PTneWhLl5pPtVfNWQUVmAMA',
    appId: '1:646409806499:web:1697987aa7178592c99516',
    messagingSenderId: '646409806499',
    projectId: 'internship-83561',
    authDomain: 'internship-83561.firebaseapp.com',
    storageBucket: 'internship-83561.firebasestorage.app',
    measurementId: 'G-F0WKQH9NPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgjT1sVbgg5xJdz0ckMPcndV-Bo2XgroE',
    appId: '1:646409806499:android:3c515e19fcd2d609c99516',
    messagingSenderId: '646409806499',
    projectId: 'internship-83561',
    storageBucket: 'internship-83561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVKHS6uzab5nbnV3K683tQhDx7SW5jLsc',
    appId: '1:646409806499:ios:dbf44a0ea98374b5c99516',
    messagingSenderId: '646409806499',
    projectId: 'internship-83561',
    storageBucket: 'internship-83561.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVKHS6uzab5nbnV3K683tQhDx7SW5jLsc',
    appId: '1:646409806499:ios:dbf44a0ea98374b5c99516',
    messagingSenderId: '646409806499',
    projectId: 'internship-83561',
    storageBucket: 'internship-83561.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeajpoChs9PTneWhLl5pPtVfNWQUVmAMA',
    appId: '1:646409806499:web:41663e3058a381d8c99516',
    messagingSenderId: '646409806499',
    projectId: 'internship-83561',
    authDomain: 'internship-83561.firebaseapp.com',
    storageBucket: 'internship-83561.firebasestorage.app',
    measurementId: 'G-KSTM4XJY6B',
  );
}
